name: Context examples

on: ['push']

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:      
      - name: "My step"
        run: |
          echo "Hello $MY_ACTION"
          echo "Actor $MY_ACTOR"
        env:
            MY_ACTION: ${{ github.action }}
            MY_ACTOR: ${{ github.actor }}


  