name: Manual Trigger with Params

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        type: string
      greeting:
        description: 'Type of greeting'
        required: true
        type: string
      data:
        description: 'Base64 encoded content of a file'
        required: false
        type: string
        default: 'SGVsbG8sIHdvcmxkIQ=='
      message:
        description: 'The message to echo'     
        required: false
        default: 'Hello, echo world!'  

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Decode File Content
        run: |
          echo "${{ inputs.data }}" | base64 --decode > ./decoded_file.txt
      - name: Display Greeting
        run: |
          echo "${{ inputs.greeting }}, ${{ inputs.name }}!"
      - name: Display File Content
        run: |
          echo "Contents of the file:"
          cat ./decoded_file.txt
# added
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print the message
        run: echo "${{ github.event.inputs.message }}"

#print      
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print the message
        run: echo "${{ github.event.inputs.message }}"