name: "repository_dispatch allows Webhook events"

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Run a script
        run: 'echo "Event of type: $GITHUB_EVENT_NAME"'

# curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token Personal_access_token_classic" -d "{\"event_type\": \"webhook\", \"client_payload\": {\"key\": \"value\"}}" https://api.github.com/repos/v-lucianos/Github-Examples/dispatches
